#!/usr/bin/dash -eu
# SPDX-License-Identifier: GPL-3.0-or-later
while IFS== read -r key value; do
  if test "$key" = url; then
    url=$value
  elif test "$key" = protocol; then
    protocol=$value
  elif test "$key" = host; then
    host=$value
  elif test "$key" = path; then
    path=$value
  fi
done
if test -z ${url:-}; then
  url=$protocol://$host/$path
fi

pass decrypt git | sh -s "$url" | {
  read -r file
  pass decrypt "$file" | {
    read -r password
    read -r username
    printf 'username=%s\npassword=%s\n' "$username" "$password"
  }
}
