#!/usr/bin/dash -eu
# SPDX-License-Identifier: GPL-3.0-or-later
pass decrypt $@ | {
  read -r password
  printf %s "$password" | {
    if test -t 1; then
      if test -n "${WAYLAND_DISPLAY:-}"; then
        wl-copy --primary --paste-once --foreground
      else
        xclip -in -rmlastnl -loops 1 -selection primary -verbose 2>/dev/null
      fi
    else
      cat
    fi
  }
}
